apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-evcl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0011-tenant/tkrw-pr714-0075-0011-app/devfile-sample-evcl@sha256:af28de9a5daa87ed161fb5c0e723812778cb62805ebefac0d32130bc7110a5f4
        name: my-nodejs
        resources: {}
status: {}
